ScreenManager:
    WelcomeScreen:
    DateScreen:
    ResultScreen:

<WelcomeScreen>:
    _welcome_screen_text_: welcome_screen
    name: 'my_welcome_screen'
    Label:
        id: welcome_screen
        Image: 
            source: 'images/bar_path_original.png'
            size: self.parent.width, self.parent.height
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

<DateScreen>:
    _date_screen_text_: date_screen
    name: 'my_date_screen'
    Label:
        id: date_screen
        text: "This is the date selection screen"
    BoxLayout:
        size_hint: 0.1, 0.5
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        MDRaisedButton:
            text: 'MDButton1'
            on_press: self.parent.parent.on_press()

<ResultScreen>:
    _result_screen_text_: result_screen
    name: 'my_result_screen'
    Label:
        id: result_screen
        text: "This is where the result will be displayed"