<BoxBarPathLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        
        padding: 50
        spacing: 10

        Button:
            text: "Hello World"
        Button:
            text: "Hello World2"
        Button:
            text: "Hello World3"
            pos_hint: {'center_x': 0.5}
            size_hint: (None, None)
            width: 100
            height: 50


